apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume
    labels:
      type: local
spec:
  storageClassName: hostpath
    capacity:
      storage: 50Mi
    accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/webserver"